// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllfjWmyxI4X-v_ZS2QjWzEpD1ilEPKl0',
    appId: '1:806388050369:web:17a547ac965f6f3703a740',
    messagingSenderId: '806388050369',
    projectId: 'emiranonotes',
    authDomain: 'emiranonotes.firebaseapp.com',
    storageBucket: 'emiranonotes.firebasestorage.app',
    measurementId: 'G-407ZPNRLH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXA4b4RtnZZ-ZqKAAwBjISvu9PC435FPI',
    appId: '1:806388050369:android:7712a99c873601e103a740',
    messagingSenderId: '806388050369',
    projectId: 'emiranonotes',
    storageBucket: 'emiranonotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdreOo62qAB3422slT3Mqa9hQd8ZnsR_I',
    appId: '1:806388050369:ios:7ec0499bbf12821603a740',
    messagingSenderId: '806388050369',
    projectId: 'emiranonotes',
    storageBucket: 'emiranonotes.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdreOo62qAB3422slT3Mqa9hQd8ZnsR_I',
    appId: '1:806388050369:ios:7ec0499bbf12821603a740',
    messagingSenderId: '806388050369',
    projectId: 'emiranonotes',
    storageBucket: 'emiranonotes.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBllfjWmyxI4X-v_ZS2QjWzEpD1ilEPKl0',
    appId: '1:806388050369:web:f0e26343d42e3f6d03a740',
    messagingSenderId: '806388050369',
    projectId: 'emiranonotes',
    authDomain: 'emiranonotes.firebaseapp.com',
    storageBucket: 'emiranonotes.firebasestorage.app',
    measurementId: 'G-ZM92XNZT3N',
  );
}
