final List<Map<String, Object>> products = [
  {
    "title": "Men's Nike Wear",
    "prize": 11.2,
    "sizes": [8, 9, 10, 11],
    "imageUrl": "assets/images/image_1.jpg",
    "company": "addidas",
    "id": 1,
  },
  {
    "title": "Nike Men Shoes",
    "prize": 22.2,
    "sizes": [22, 3],
    "imageUrl": "assets/images/image_2.jpg",
    "company": "Gucci",
    "id": 2,
  },
  {
    "title": "Women Sport Wear",
    "prize": 33.2,
    "sizes": [8, 9],
    "imageUrl": "assets/images/image_3.jpg",
    "company": "Puma",
    "id": 3,
  },
  {
    "title": "Sports Wear",
    "prize": 44.2,
    "sizes": [8],
    "imageUrl": "assets/images/image_4.jpg",
    "company": "Nike",
    "id": 4,
  },
  {
    "title": "Men's Nike Wear",
    "prize": 11.2,
    "sizes": [8, 9, 10, 11],
    "imageUrl": "assets/images/image_1.jpg",
    "company": "addidas",
    "id": 1,
  },
  {
    "title": "Nike Men Shoes",
    "prize": 22.2,
    "sizes": [22, 3],
    "imageUrl": "assets/images/image_2.jpg",
    "company": "Gucci",
    "id": 2,
  },
  {
    "title": "Women Sport Wear",
    "prize": 33.2,
    "sizes": [8, 9],
    "imageUrl": "assets/images/image_3.jpg",
    "company": "Puma",
    "id": 3,
  },
  {
    "title": "Sports Wear",
    "prize": 44.2,
    "sizes": [8],
    "imageUrl": "assets/images/image_4.jpg",
    "company": "Nike",
    "id": 4,
  },
];

final List<Map<String, Object>> cart = [];
